version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/campuscompass
      - JWT_SECRET=your_jwt_secret_for_development
    volumes:
      - ./campuscompass/back:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"  # Changed from "80:80" to avoid conflicts
    volumes:
      - ./campuscompass/front:/app/src  # More specific volume mapping
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=campuscompass
    restart: unless-stopped

volumes:
  mongo-data: